name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Обновили до v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Обновили до v5 (актуальная)
        with:
          python-version: '3.10'

      - name: Install SDK
        run: pip install flet

      - name: Build APK
        run: |
          # Устанавливаем зависимости из твоего файла, чтобы сборщик их видел
          pip install -r requirements.txt
          
          # Упрощенная команда сборки. 
          # Flet сам найдет иконку в assets/icon.png, если она там лежит.
          flet build apk --project "NetProfileScan" --org "com.zaruzhnikov.netprofile"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # ВОТ ТУТ ГЛАВНОЕ ИСПРАВЛЕНИЕ
        with:
          name: app-release
          path: build/apk/*.apk
